#include "hal_base.h"
#include "cpu_config.h"

/**
 * 描述：使能相关外设时钟
*/
U32 Pclk_DrvInit()
{
#if defined(MMU_GPIO0_ADDR)
    MODIFY_REG(PMU1CRU->GATE_CON[5],
            PMU1CRU_GATE_CON05_PCLK_GPIO0_EN_MASK |
            PMU1CRU_GATE_CON05_DBCLK_GPIO0_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_GPIO1_ADDR)
    MODIFY_REG(CRU->GATE_CON[16],
            CRU_GATE_CON16_PCLK_GPIO1_EN_MASK |
            CRU_GATE_CON16_DBCLK_GPIO1_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_GPIO2_ADDR)
    MODIFY_REG(CRU->GATE_CON[17],
            CRU_GATE_CON17_PCLK_GPIO2_EN_MASK |
            CRU_GATE_CON17_DBCLK_GPIO2_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_GPIO3_ADDR)
    MODIFY_REG(CRU->GATE_CON[17],
            CRU_GATE_CON17_PCLK_GPIO3_EN_MASK |
            CRU_GATE_CON17_DBCLK_GPIO3_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_GPIO4_ADDR)
    MODIFY_REG(CRU->GATE_CON[17],
            CRU_GATE_CON17_PCLK_GPIO4_EN_MASK |
            CRU_GATE_CON17_DBCLK_GPIO4_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_UART0_ADDR)
    MODIFY_REG(PMU1CRU->GATE_CON[2],
            PMU1CRU_GATE_CON02_PCLK_UART0_EN_MASK |
            PMU1CRU_GATE_CON02_SCLK_UART0_EN_MASK |
            PMU1CRU_GATE_CON02_CLK_UART0_FRAC_EN_MASK |
            PMU1CRU_GATE_CON02_CLK_UART0_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_UART1_ADDR)
    MODIFY_REG(CRU->GATE_CON[12],
            CRU_GATE_CON12_PCLK_UART1_EN_MASK |
            CRU_GATE_CON12_SCLK_UART1_EN_MASK |
            CRU_GATE_CON12_CLK_UART1_FRAC_EN_MASK |
            CRU_GATE_CON12_CLK_UART1_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_UART2_ADDR)
    MODIFY_REG(CRU->GATE_CON[12],
            CRU_GATE_CON12_PCLK_UART2_EN_MASK |
            CRU_GATE_CON12_CLK_UART2_FRAC_EN_MASK |
            CRU_GATE_CON12_CLK_UART2_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[13],
            CRU_GATE_CON13_SCLK_UART2_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_UART3_ADDR)
    MODIFY_REG(CRU->GATE_CON[12],
            CRU_GATE_CON12_PCLK_UART3_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[13],
            CRU_GATE_CON13_SCLK_UART3_EN_MASK |
            CRU_GATE_CON13_CLK_UART3_FRAC_EN_MASK |
            CRU_GATE_CON13_CLK_UART3_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_UART4_ADDR)
    MODIFY_REG(CRU->GATE_CON[12],
            CRU_GATE_CON12_PCLK_UART4_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[13],
            CRU_GATE_CON13_SCLK_UART4_EN_MASK |
            CRU_GATE_CON13_CLK_UART4_FRAC_EN_MASK |
            CRU_GATE_CON13_CLK_UART4_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_UART5_ADDR)
    MODIFY_REG(CRU->GATE_CON[12],
            CRU_GATE_CON12_PCLK_UART5_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[13],
            CRU_GATE_CON13_SCLK_UART5_EN_MASK |
            CRU_GATE_CON13_CLK_UART5_FRAC_EN_MASK |
            CRU_GATE_CON13_CLK_UART5_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_UART6_ADDR)
    MODIFY_REG(CRU->GATE_CON[12],
            CRU_GATE_CON12_PCLK_UART6_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[13],
            CRU_GATE_CON13_SCLK_UART6_EN_MASK |
            CRU_GATE_CON13_CLK_UART6_FRAC_EN_MASK |
            CRU_GATE_CON13_CLK_UART6_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_UART7_ADDR)
    MODIFY_REG(CRU->GATE_CON[12],
            CRU_GATE_CON12_PCLK_UART7_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[13],
            CRU_GATE_CON13_SCLK_UART7_EN_MASK |
            CRU_GATE_CON13_CLK_UART7_FRAC_EN_MASK |
            CRU_GATE_CON13_CLK_UART7_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_UART8_ADDR)
    MODIFY_REG(CRU->GATE_CON[12],
            CRU_GATE_CON12_PCLK_UART8_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[14],
            CRU_GATE_CON14_SCLK_UART8_EN_MASK |
            CRU_GATE_CON14_CLK_UART8_FRAC_EN_MASK |
            CRU_GATE_CON14_CLK_UART8_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_UART9_ADDR)
    MODIFY_REG(CRU->GATE_CON[12],
            CRU_GATE_CON12_PCLK_UART9_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[14],
            CRU_GATE_CON14_SCLK_UART9_EN_MASK |
            CRU_GATE_CON14_CLK_UART9_FRAC_EN_MASK |
            CRU_GATE_CON14_CLK_UART9_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_TIMER_ADDR)
    MODIFY_REG(CRU->GATE_CON[15],
            CRU_GATE_CON15_CLK_BUSTIMER0_EN_MASK |
            CRU_GATE_CON15_CLK_BUSTIMER_ROOT_EN_MASK |
            CRU_GATE_CON15_PCLK_BUSTIMER0_EN_MASK |
            CRU_GATE_CON15_PCLK_BUSTIMER1_EN_MASK, 0xffff0000);
        
    MODIFY_REG(CRU->GATE_CON[16],
            CRU_GATE_CON16_CLK_BUSTIMER1_EN_MASK |
            CRU_GATE_CON16_CLK_BUSTIMER2_EN_MASK |
            CRU_GATE_CON16_CLK_BUSTIMER3_EN_MASK |
            CRU_GATE_CON16_CLK_BUSTIMER4_EN_MASK |
            CRU_GATE_CON16_CLK_BUSTIMER5_EN_MASK |
            CRU_GATE_CON16_CLK_BUSTIMER6_EN_MASK |
            CRU_GATE_CON16_CLK_BUSTIMER7_EN_MASK |
            CRU_GATE_CON16_CLK_BUSTIMER8_EN_MASK |
            CRU_GATE_CON16_CLK_BUSTIMER9_EN_MASK |
            CRU_GATE_CON16_CLK_BUSTIMER10_EN_MASK |
            CRU_GATE_CON16_CLK_BUSTIMER11_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_SPI0_ADDR)
    MODIFY_REG(CRU->GATE_CON[14],
            CRU_GATE_CON14_CLK_SPI0_EN_MASK | CRU_GATE_CON14_PCLK_SPI0_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_SPI1_ADDR)
    MODIFY_REG(CRU->GATE_CON[14],
            CRU_GATE_CON14_CLK_SPI1_EN_MASK | CRU_GATE_CON14_PCLK_SPI1_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_SPI2_ADDR)
    MODIFY_REG(CRU->GATE_CON[14],
            CRU_GATE_CON14_CLK_SPI2_EN_MASK | CRU_GATE_CON14_PCLK_SPI2_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_SPI3_ADDR)
    MODIFY_REG(CRU->GATE_CON[14],
            CRU_GATE_CON14_CLK_SPI3_EN_MASK | CRU_GATE_CON14_PCLK_SPI3_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_SPI4_ADDR)
    MODIFY_REG(CRU->GATE_CON[14],
            CRU_GATE_CON14_CLK_SPI4_EN_MASK | CRU_GATE_CON14_PCLK_SPI4_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_I2C0_ADDR)
    MODIFY_REG(PMU1CRU->GATE_CON[2],
            PMU1CRU_GATE_CON02_PCLK_I2C0_EN_MASK |
            PMU1CRU_GATE_CON02_CLK_I2C0_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_I2C1_ADDR)
    MODIFY_REG(CRU->GATE_CON[10],
            CRU_GATE_CON10_PCLK_I2C1_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[11],
            CRU_GATE_CON11_CLK_I2C1_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_I2C2_ADDR)
    MODIFY_REG(CRU->GATE_CON[10],
            CRU_GATE_CON10_PCLK_I2C2_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[11],
            CRU_GATE_CON11_CLK_I2C2_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_I2C3_ADDR)
    MODIFY_REG(CRU->GATE_CON[10],
            CRU_GATE_CON10_PCLK_I2C3_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[11],
            CRU_GATE_CON11_CLK_I2C3_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_I2C4_ADDR)
    MODIFY_REG(CRU->GATE_CON[10],
            CRU_GATE_CON10_PCLK_I2C4_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[11],
            CRU_GATE_CON11_CLK_I2C4_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_I2C5_ADDR)
    MODIFY_REG(CRU->GATE_CON[10],
            CRU_GATE_CON10_PCLK_I2C5_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[11],
            CRU_GATE_CON11_CLK_I2C5_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_I2C6_ADDR)
    MODIFY_REG(CRU->GATE_CON[10],
            CRU_GATE_CON10_PCLK_I2C6_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[11],
            CRU_GATE_CON11_CLK_I2C6_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_I2C7_ADDR)
    MODIFY_REG(CRU->GATE_CON[10],
            CRU_GATE_CON10_PCLK_I2C7_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[11],
            CRU_GATE_CON11_CLK_I2C7_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_I2C8_ADDR)
    MODIFY_REG(CRU->GATE_CON[10],
            CRU_GATE_CON10_PCLK_I2C8_EN_MASK, 0xffff0000);
    MODIFY_REG(CRU->GATE_CON[11],
            CRU_GATE_CON11_CLK_I2C8_EN_MASK, 0xffff0000);
#endif

#if defined(MMU_CAN0_ADDR)
    MODIFY_REG(CRU->GATE_CON[11],
               CRU_GATE_CON11_CLK_CAN0_EN_MASK | CRU_GATE_CON11_PCLK_CAN0_EN_MASK, 0xffff0000);

    /* 假设GPLL频率1200M，设置CAN时钟频率为200M */
    MODIFY_REG(CRU->CLKSEL_CON[39],
               CRU_CLKSEL_CON39_CLK_CAN0_DIV_MASK | CRU_CLKSEL_CON39_CLK_CAN0_SEL_MASK,
               (5 << CRU_CLKSEL_CON39_CLK_CAN0_DIV_SHIFT) | (0 << CRU_CLKSEL_CON39_CLK_CAN0_SEL_SHIFT) | 0xFFFF0000);
#endif

#if defined(MMU_CAN1_ADDR)
    MODIFY_REG(CRU->GATE_CON[11],
               CRU_GATE_CON11_CLK_CAN1_EN_MASK | CRU_GATE_CON11_PCLK_CAN1_EN_MASK, 0xffff0000);
    
    /* 假设GPLL频率1200M，设置CAN时钟频率为200M */
    MODIFY_REG(CRU->CLKSEL_CON[39],
               CRU_CLKSEL_CON39_CLK_CAN1_DIV_MASK | CRU_CLKSEL_CON39_CLK_CAN1_SEL_MASK,
               (5 << CRU_CLKSEL_CON39_CLK_CAN1_DIV_SHIFT) | (0 << CRU_CLKSEL_CON39_CLK_CAN1_SEL_SHIFT) | 0xFFFF0000);
#endif

#if defined(MMU_CAN2_ADDR)
    MODIFY_REG(CRU->GATE_CON[11],
               CRU_GATE_CON11_CLK_CAN2_EN_MASK | CRU_GATE_CON11_PCLK_CAN2_EN_MASK, 0xffff0000);
    
    /* 假设GPLL频率1200M，设置CAN时钟频率为200M */
    MODIFY_REG(CRU->CLKSEL_CON[40],
               CRU_CLKSEL_CON40_CLK_CAN2_DIV_MASK | CRU_CLKSEL_CON40_CLK_CAN2_SEL_MASK,
               (5 << CRU_CLKSEL_CON40_CLK_CAN2_DIV_SHIFT) | (0 << CRU_CLKSEL_CON40_CLK_CAN2_SEL_SHIFT) | 0xFFFF0000);
#endif

#if defined(MMU_GMAC0_ADDR)
    // CLKSEL_CON15 0x0000bb9d 使用reset默认值
    MODIFY_REG(CRU->CLKSEL_CON[15], 0, CRU_CLKSEL_CON15_MCLK_GMAC0_OUT_SEL_MASK | CRU_CLKSEL_CON15_REFCLKO25M_ETH0_OUT_SEL_MASK \
            | (0x1D << CRU_CLKSEL_CON15_MCLK_GMAC0_OUT_DIV_SHIFT) | (0x3B << CRU_CLKSEL_CON15_REFCLKO25M_ETH0_OUT_DIV_SHIFT) | 0xffff0000);
    // GATE_CON5 0x00000000 使用reset默认值
    MODIFY_REG(CRU->GATE_CON[5], CRU_GATE_CON05_MCLK_GMAC0_OUT_EN_MASK | CRU_GATE_CON05_REFCLKO25M_ETH0_OUT_EN_MASK, 0xffff0000);
    // GATE_CON34 0x00000000 使用reset默认值
    MODIFY_REG(CRU->GATE_CON[34], CRU_GATE_CON34_CLK_GMAC0_PTP_REF_EN_MASK, 0xffff0000);
    // GATE_CON32 0x00000000 使用reset默认值
    MODIFY_REG(CRU->GATE_CON[32], CRU_GATE_CON32_PCLK_GMAC0_EN_MASK | CRU_GATE_CON32_ACLK_GMAC0_EN_MASK, 0xffff0000);
    // 注意softrst_con没有0号寄存器，所以此处31与trm文档中32对应
    MODIFY_REG(CRU->SOFTRST_CON[31], CRU_SOFTRST_CON32_ARESETN_GMAC0_MASK, 0xffff0000);
#endif

#if defined(MMU_GMAC1_ADDR)
    // CLKSEL_CON16 使用reset默认值
    MODIFY_REG(CRU->CLKSEL_CON[16], 0, (0x3B << CRU_CLKSEL_CON16_REFCLKO25M_ETH1_OUT_DIV_SHIFT) | CRU_CLKSEL_CON16_REFCLKO25M_ETH1_OUT_SEL_MASK | 0xffff0000);
    // GATE_CON5 使用reset默认值
    MODIFY_REG(CRU->GATE_CON[5], CRU_GATE_CON05_REFCLKO25M_ETH1_OUT_EN_MASK, 0xffff0000);
    // CLKSEL_CON81 使用reset默认值
    MODIFY_REG(CRU->CLKSEL_CON[81], 0, (0x0e << CRU_CLKSEL_CON81_CLK_GMAC1_PTP_REF_DIV_SHIFT) | 0xffff0000);
    // GATE_CON34 使用reset默认值
    MODIFY_REG(CRU->GATE_CON[34], CRU_GATE_CON34_CLK_GMAC1_PTP_REF_EN_MASK, 0xffff0000);
    // GATE_CON32 使用reset默认值
    MODIFY_REG(CRU->GATE_CON[32], (CRU_GATE_CON32_PCLK_GMAC1_EN_MASK | CRU_GATE_CON32_ACLK_GMAC1_EN_MASK), 0xffff0000);
    // 注意softrst_con没有0号寄存器，所以此处31与trm文档中32对应
    MODIFY_REG(CRU->SOFTRST_CON[31], CRU_SOFTRST_CON32_ARESETN_GMAC1_MASK, 0xffff0000);
#endif

#if defined(MMU_GMAC1_ADDR)|| defined(MMU_GMAC0_ADDR)
    // CLKSEL_CON83 使用reset默认值
    MODIFY_REG(CRU->CLKSEL_CON[83], 0, (0x0b << CRU_CLKSEL_CON83_CLK_GMAC_125M_CRU_I_DIV_SHIFT) | CRU_CLKSEL_CON83_CLK_GMAC_125M_CRU_I_SEL_MASK | 0xffff0000);
    // CLKSEL_CON84 使用reset默认值
    MODIFY_REG(CRU->CLKSEL_CON[84], 0, (0x1D << CRU_CLKSEL_CON84_CLK_GMAC_50M_CRU_I_DIV_SHIFT) | CRU_CLKSEL_CON84_CLK_GMAC_50M_CRU_I_SEL_MASK | 0xffff0000);
    // GATE_CON35 使用reset默认值
    MODIFY_REG(CRU->GATE_CON[35], CRU_GATE_CON35_CLK_GMAC_50M_CRU_EN_MASK | CRU_GATE_CON35_CLK_GMAC_125M_CRU_EN_MASK, 0xffff0000);
#endif
    
    return OS_OK;
}
