#ifndef CPU_CONFIG_H
#define CPU_CONFIG_H

#include <prt_cache_external.h>
#include "fparameters_comm.h"
#include "prt_buildef.h"

#define MMU_OPENAMP_ADDR    0x8c800000ULL
#define OPENAMP_SHM_SIZE    0x1800000U          //24M

#define MMU_IMAGE_ADDR  0xC0000000ULL

#define MMU_GIC_ADDR    0x30800000ULL

#define MMU_IOPAD_ADDR  FIOPAD_BASE_ADDR

#define MMU_GPIO0_ADDR  FGPIO0_BASE_ADDR
#define MMU_GPIO1_ADDR  FGPIO1_BASE_ADDR
#define MMU_GPIO2_ADDR  FGPIO2_BASE_ADDR
#define MMU_GPIO3_ADDR  FGPIO3_BASE_ADDR
#define MMU_GPIO4_ADDR  FGPIO4_BASE_ADDR
#define MMU_GPIO5_ADDR  FGPIO5_BASE_ADDR

#define MMU_MIO0_ADDR    FMIO_BASE_ADDR(0)
// #define MMU_MIO1_ADDR    FMIO_BASE_ADDR(1)
// #define MMU_MIO2_ADDR    FMIO_BASE_ADDR(2)
// #define MMU_MIO3_ADDR    FMIO_BASE_ADDR(3)
// #define MMU_MIO4_ADDR    FMIO_BASE_ADDR(4)
// #define MMU_MIO5_ADDR    FMIO_BASE_ADDR(5)
// #define MMU_MIO6_ADDR    FMIO_BASE_ADDR(6)
// #define MMU_MIO7_ADDR    FMIO_BASE_ADDR(7)
// #define MMU_MIO8_ADDR    FMIO_BASE_ADDR(8)
#define MMU_MIO9_ADDR    FMIO_BASE_ADDR(9)
// #define MMU_MIO10_ADDR   FMIO_BASE_ADDR(10)
// #define MMU_MIO11_ADDR   FMIO_BASE_ADDR(11)
// #define MMU_MIO12_ADDR   FMIO_BASE_ADDR(12)
// #define MMU_MIO13_ADDR   FMIO_BASE_ADDR(13)
// #define MMU_MIO14_ADDR   FMIO_BASE_ADDR(14)
// #define MMU_MIO15_ADDR   FMIO_BASE_ADDR(15)

// #define MMU_UART0_ADDR  FUART0_BASE_ADDR
#define MMU_UART1_ADDR  FUART1_BASE_ADDR
// #define MMU_UART2_ADDR  FUART2_BASE_ADDR
// #define MMU_UART3_ADDR  FUART3_BASE_ADDR

// #define MMU_I2C0_ADDR   FI2C0_BASE_ADDR
// #define MMU_I2C1_ADDR   FI2C1_BASE_ADDR
// #define MMU_I2C2_ADDR   FI2C2_BASE_ADDR

#define MMU_SPI0_ADDR   FSPI0_BASE_ADDR
// #define MMU_SPI1_ADDR   FSPI1_BASE_ADDR
// #define MMU_SPI2_ADDR   FSPI2_BASE
// #define MMU_SPI3_ADDR   FSPI3_BASE

#define MMU_CAN0_ADDR   FCAN0_BASE_ADDR
// #define MMU_CAN1_ADDR   FCAN1_BASE_ADDR

#define MMU_TIMER0_ADDR  FTIMER_TACHO_BASE_ADDR(0)
// #define MMU_TIMER1_ADDR  FTIMER_TACHO_BASE_ADDR(1)
// #define MMU_TIMER2_ADDR  FTIMER_TACHO_BASE_ADDR(2)
// #define MMU_TIMER3_ADDR  FTIMER_TACHO_BASE_ADDR(3)

// #define MMU_FXMAC0_ADDR   FXMAC0_BASE_ADDR
// #define MMU_FXMAC2_ADDR   FXMAC2_BASE_ADDR

#define MMU_FXMAC3_ADDR   FXMAC3_BASE_ADDR
#define MMU_LOCALBUS_ADDR 0x28007000ULL

#define OS_GIC_VER  3
#define SICR_ADDR_OFFSET_PER_CORE   0x20000U
#define GIC_REG_BASE_ADDR MMU_GIC_ADDR

#define GICD_CTLR_S_ADDR        (GIC_REG_BASE_ADDR + 0x0000U)
#define GICD_IGROUPN_ADDR       (GIC_REG_BASE_ADDR + 0x0080U)
#define GICD_ISENABLER0_ADDR    (GIC_REG_BASE_ADDR + 0x0100U)
#define GICD_ICENABLER0_ADDR    (GIC_REG_BASE_ADDR + 0x0180U)
#define GICD_IPRIORITYN_ADDR    (GIC_REG_BASE_ADDR + 0x0400U)
#define GICD_IGRPMODRN_ADDR     (GIC_REG_BASE_ADDR + 0x0D00U)
#define GICD_IROUTER            (GIC_REG_BASE_ADDR + 0x6100U)

#define GICR_BASE0      (GIC_REG_BASE_ADDR + 0x80000U)
#define GICR_BASE1      (GIC_REG_BASE_ADDR + 0x90000U)

#define GICR_CTRL_ADDR      (GICR_BASE0 + 0x0000U)
#define GICR_WAKER_ADDR     (GICR_BASE0 + 0x0014U)

#define GICR_IGROUPR0_ADDR      (GICR_BASE1 + 0x0080U)
#define GICR_ISENABLER0_ADDR    (GICR_BASE1 + 0x0100U)
#define GICR_ICENABLER0_ADDR    (GICR_BASE1 + 0x0180U)
#define GICR_IGRPMODR0_ADDR     (GICR_BASE1 + 0x0D00U)

#if defined(GUEST_OS_XEN)
#define TEST_CLK_INT 27
#else
#define TEST_CLK_INT 30
#endif

#define MAX_INT_NUM 266
#define MIN_GIC_SPI_NUM 32
#define SICD_IGROUP_INT_NUM 32
#define SICD_REG_SIZE 4

#define GROUP_MAX_BPR   0x7U
#define GROUP0_BP   0
#define GROUP1_BP   0

#define PRIO_MASK_LEVEL 0xFFU

#define ICC_SRE_EL1 S3_0_C12_C12_5
#define ICC_BPR0_EL1 S3_0_C12_C8_3
#define ICC_BPR1_EL1 S3_0_C12_C12_3
#define ICC_IGRPEN1_EL1 S3_0_C12_C12_7
#define ICC_PMR_EL1 S3_0_C4_C6_0

#define PARAS_TO_STRING(x...) #x
#define REG_ALIAS(x...) PARAS_TO_STRING(x)

#define GIC_REG_READ(addr) (*(volatile U32 *)((uintptr_t)(addr)))
#define GIC_REG_WRITE(addr, data) (*(volatile U32 *)((uintptr_t)(addr)) = (U32)(data))

#endif
