
//*****************************************************************************
//
// WARNING: Automatically generated file, don't modify anymore!!!
//
// Copyright (c) 2021-2029 Semidrive Incorporated.  All rights reserved.
// Software License Agreement
//
//*****************************************************************************

#ifndef IRQ_NUM_H
#define IRQ_NUM_H

#define INT_BASE                                                     0xF5410000
#define DMA1_INTR_NUM                                                32
#define DMA2_INTR_NUM                                                33
#define DMA3_INTR_NUM                                                34
#define DMA4_INTR_NUM                                                35
#define DMA5_INTR_NUM                                                36
#define DMA6_INTR_NUM                                                37
#define DMA7_INTR_NUM                                                38
#define DMA8_INTR_NUM                                                39
#define SEM1_O_SEM_INTR_NUM                                          46
#define SEM2_O_SEM_INTR_NUM                                          47
#define SEM1_O_SEM_CPU_INTR_NUM                                      46
#define SEM2_O_SEM_CPU_INTR_NUM                                      47
#define UART1_INTR_NUM                                               48
#define UART2_INTR_NUM                                               49
#define UART3_INTR_NUM                                               50
#define UART4_INTR_NUM                                               51
#define UART5_INTR_NUM                                               52
#define UART6_INTR_NUM                                               53
#define UART7_INTR_NUM                                               54
#define UART8_INTR_NUM                                               55
#define UART9_INTR_NUM                                               56
#define UART10_INTR_NUM                                              57
#define UART11_INTR_NUM                                              58
#define UART12_INTR_NUM                                              59
#define UART13_INTR_NUM                                              60
#define UART14_INTR_NUM                                              61
#define UART15_INTR_NUM                                              62
#define UART16_INTR_NUM                                              63
#define I2C1_IC_INTR_NUM                                             64
#define I2C2_IC_INTR_NUM                                             65
#define I2C3_IC_INTR_NUM                                             66
#define I2C4_IC_INTR_NUM                                             67
#define I2C5_IC_INTR_NUM                                             68
#define I2C6_IC_INTR_NUM                                             69
#define I2C7_IC_INTR_NUM                                             70
#define I2C8_IC_INTR_NUM                                             71
#define I2C9_IC_INTR_NUM                                             72
#define I2C10_IC_INTR_NUM                                            73
#define I2C11_IC_INTR_NUM                                            74
#define I2C12_IC_INTR_NUM                                            75
#define I2C13_IC_INTR_NUM                                            76
#define I2C14_IC_INTR_NUM                                            77
#define I2C15_IC_INTR_NUM                                            78
#define I2C16_IC_INTR_NUM                                            79
#define SPI1_O_SSI_INTR_NUM                                          80
#define SPI2_O_SSI_INTR_NUM                                          81
#define SPI3_O_SSI_INTR_NUM                                          82
#define SPI4_O_SSI_INTR_NUM                                          83
#define SPI5_O_SSI_INTR_NUM                                          84
#define SPI6_O_SSI_INTR_NUM                                          85
#define SPI7_O_SSI_INTR_NUM                                          86
#define SPI8_O_SSI_INTR_NUM                                          87
#define OSPI1_INTR_NUM                                               88
#define OSPI2_INTR_NUM                                               89
#define I2S_SC1_INTR_NUM                                             90
#define I2S_SC2_INTR_NUM                                             91
#define I2S_SC3_INTR_NUM                                             92
#define I2S_SC4_INTR_NUM                                             93
#define I2S_SC5_INTR_NUM                                             94
#define I2S_SC6_INTR_NUM                                             95
#define I2S_SC7_INTR_NUM                                             96
#define I2S_SC8_INTR_NUM                                             97
#define I2S_MC1_INTR_NUM                                             98
#define I2S_MC2_INTR_NUM                                             99
#define SPDIF1_INTR_NUM                                              100
#define SPDIF2_INTR_NUM                                              101
#define SPDIF3_INTR_NUM                                              102
#define SPDIF4_INTR_NUM                                              103
#define USB1_O_USB1_USB3_INTR_NUM                                    104
#define USB1_O_USB1_USB3_WAKEUP_INTR_NUM                             105
#define USB1_O_USB1_USB3_CHGDET_INTR_NUM                             106
#define USB2_O_USB2_USB3_INTR_NUM                                    107
#define USB2_O_USB2_USB3_WAKEUP_INTR_NUM                             108
#define USB2_O_USB2_USB3_CHGDET_INTR_NUM                             109
#define PCIE1_O_PCIEX2_IRQ_A_INTR_NUM                                110
#define PCIE1_O_PCIEX2_IRQ_B_INTR_NUM                                111
#define PCIE1_O_PCIEX2_IRQ_C_INTR_NUM                                112
#define PCIE1_O_PCIEX2_IRQ_D_INTR_NUM                                113
#define PCIE1_O_PCIEX2_IRQ_LINK_DOWN_INTR_NUM                        114
#define PCIE1_O_PCIEX2_IRQ_EDMA_0_INTR_NUM                           115
#define PCIE1_O_PCIEX2_IRQ_EDMA_1_INTR_NUM                           116
#define PCIE1_O_PCIEX2_IRQ_EDMA_2_INTR_NUM                           117
#define PCIE1_O_PCIEX2_IRQ_EDMA_3_INTR_NUM                           118
#define PCIE1_O_PCIEX2_IRQ_EDMA_4_INTR_NUM                           119
#define PCIE1_O_PCIEX2_IRQ_EDMA_5_INTR_NUM                           120
#define PCIE1_O_PCIEX2_IRQ_EDMA_6_INTR_NUM                           121
#define PCIE1_O_PCIEX2_IRQ_EDMA_7_INTR_NUM                           122
#define PCIE1_O_PCIEX2_SAFETY_UNCORR_INTR_NUM                        123
#define PCIE1_O_PCIEX2_SAFETY_CORR_INTR_NUM                          124
#define PCIE2_O_PCIEX1_IRQ_A_INTR_NUM                                125
#define PCIE2_O_PCIEX1_IRQ_B_INTR_NUM                                126
#define PCIE2_O_PCIEX1_IRQ_C_INTR_NUM                                127
#define PCIE2_O_PCIEX1_IRQ_D_INTR_NUM                                128
#define PCIE2_O_PCIEX1_IRQ_LINK_DOWN_INTR_NUM                        129
#define PCIE2_O_PCIEX1_IRQ_EDMA_0_INTR_NUM                           130
#define PCIE2_O_PCIEX1_IRQ_EDMA_1_INTR_NUM                           131
#define PCIE2_O_PCIEX1_SAFETY_UNCORR_INTR_NUM                        132
#define PCIE2_O_PCIEX1_SAFETY_CORR_INTR_NUM                          133
#define ETH1_SBD_INTR_NUM                                           134
#define ETH1_SBD_PERCH_TX_O0_INTR_NUM                               135
#define ETH1_SBD_PERCH_TX_O1_INTR_NUM                               135
#define ETH1_SBD_PERCH_TX_O2_INTR_NUM                               135
#define ETH1_SBD_PERCH_TX_O3_INTR_NUM                               135
#define ETH1_SBD_PERCH_TX_O4_INTR_NUM                               135
#define ETH1_SBD_PERCH_RX_O0_INTR_NUM                               135
#define ETH1_SBD_PERCH_RX_O1_INTR_NUM                               135
#define ETH1_SBD_PERCH_RX_O2_INTR_NUM                               135
#define ETH1_SBD_PERCH_RX_O3_INTR_NUM                               135
#define ETH1_SBD_PERCH_RX_O4_INTR_NUM                               135
#define ETH1_LPI_INTR_NUM                                           136
#define ETH1_PMT_INTR_NUM                                           136
#define ETH2_SBD_INTR_NUM                                           137
#define ETH2_SBD_PERCH_TX_O0_INTR_NUM                               138
#define ETH2_SBD_PERCH_TX_O1_INTR_NUM                               138
#define ETH2_SBD_PERCH_TX_O2_INTR_NUM                               138
#define ETH2_SBD_PERCH_TX_O3_INTR_NUM                               138
#define ETH2_SBD_PERCH_TX_O4_INTR_NUM                               138
#define ETH2_SBD_PERCH_RX_O0_INTR_NUM                               138
#define ETH2_SBD_PERCH_RX_O1_INTR_NUM                               138
#define ETH2_SBD_PERCH_RX_O2_INTR_NUM                               138
#define ETH2_SBD_PERCH_RX_O3_INTR_NUM                               138
#define ETH2_SBD_PERCH_RX_O4_INTR_NUM                               138
#define ETH2_LPI_INTR_NUM                                           139
#define ETH2_PMT_INTR_NUM                                           139
#define MSHC1_INTR_NUM                                               142
#define MSHC1_WAKEUP_INTR_NUM                                        143
#define MSHC2_INTR_NUM                                               144
#define MSHC2_WAKEUP_INTR_NUM                                        145
#define MSHC3_INTR_NUM                                               146
#define MSHC3_WAKEUP_INTR_NUM                                        147
#define MSHC4_INTR_NUM                                               148
#define MSHC4_WAKEUP_INTR_NUM                                        149
#define CANFD1_IPI_BUSOFF_INTR_NUM                                   150
#define CANFD1_IPI_ERROR_INTR_NUM                                    150
#define CANFD1_IPI_MBOR_INTR_NUM                                     150
#define CANFD1_IPI_RX_WARNING_INTR_NUM                               150
#define CANFD1_IPI_TX_WARNING_INTR_NUM                               150
#define CANFD1_IPI_WAKEIN_INTR_NUM                                   150
#define CANFD1_IPI_WAKE_MATCH_INTR_NUM                               150
#define CANFD1_IPI_WAKE_TO_INTR_NUM                                  150
#define CANFD1_IPI_BUSOFF_DONE_INTR_NUM                              150
#define CANFD1_IPI_ERROR_FD_INTR_NUM                                 150
#define CANFD2_IPI_BUSOFF_INTR_NUM                                   151
#define CANFD2_IPI_ERROR_INTR_NUM                                    151
#define CANFD2_IPI_MBOR_INTR_NUM                                     151
#define CANFD2_IPI_RX_WARNING_INTR_NUM                               151
#define CANFD2_IPI_TX_WARNING_INTR_NUM                               151
#define CANFD2_IPI_WAKEIN_INTR_NUM                                   151
#define CANFD2_IPI_WAKE_MATCH_INTR_NUM                               151
#define CANFD2_IPI_WAKE_TO_INTR_NUM                                  151
#define CANFD2_IPI_BUSOFF_DONE_INTR_NUM                              151
#define CANFD2_IPI_ERROR_FD_INTR_NUM                                 151
#define CANFD3_IPI_BUSOFF_INTR_NUM                                   152
#define CANFD3_IPI_ERROR_INTR_NUM                                    152
#define CANFD3_IPI_MBOR_INTR_NUM                                     152
#define CANFD3_IPI_RX_WARNING_INTR_NUM                               152
#define CANFD3_IPI_TX_WARNING_INTR_NUM                               152
#define CANFD3_IPI_WAKEIN_INTR_NUM                                   152
#define CANFD3_IPI_WAKE_MATCH_INTR_NUM                               152
#define CANFD3_IPI_WAKE_TO_INTR_NUM                                  152
#define CANFD3_IPI_BUSOFF_DONE_INTR_NUM                              152
#define CANFD3_IPI_ERROR_FD_INTR_NUM                                 152
#define CANFD4_IPI_BUSOFF_INTR_NUM                                   153
#define CANFD4_IPI_ERROR_INTR_NUM                                    153
#define CANFD4_IPI_MBOR_INTR_NUM                                     153
#define CANFD4_IPI_RX_WARNING_INTR_NUM                               153
#define CANFD4_IPI_TX_WARNING_INTR_NUM                               153
#define CANFD4_IPI_WAKEIN_INTR_NUM                                   153
#define CANFD4_IPI_WAKE_MATCH_INTR_NUM                               153
#define CANFD4_IPI_WAKE_TO_INTR_NUM                                  153
#define CANFD4_IPI_BUSOFF_DONE_INTR_NUM                              153
#define CANFD4_IPI_ERROR_FD_INTR_NUM                                 153
#define CANFD5_IPI_BUSOFF_INTR_NUM                                   154
#define CANFD5_IPI_ERROR_INTR_NUM                                    154
#define CANFD5_IPI_MBOR_INTR_NUM                                     154
#define CANFD5_IPI_RX_WARNING_INTR_NUM                               154
#define CANFD5_IPI_TX_WARNING_INTR_NUM                               154
#define CANFD5_IPI_WAKEIN_INTR_NUM                                   154
#define CANFD5_IPI_WAKE_MATCH_INTR_NUM                               154
#define CANFD5_IPI_WAKE_TO_INTR_NUM                                  154
#define CANFD5_IPI_BUSOFF_DONE_INTR_NUM                              154
#define CANFD5_IPI_ERROR_FD_INTR_NUM                                 154
#define CANFD6_IPI_BUSOFF_INTR_NUM                                   155
#define CANFD6_IPI_ERROR_INTR_NUM                                    155
#define CANFD6_IPI_MBOR_INTR_NUM                                     155
#define CANFD6_IPI_RX_WARNING_INTR_NUM                               155
#define CANFD6_IPI_TX_WARNING_INTR_NUM                               155
#define CANFD6_IPI_WAKEIN_INTR_NUM                                   155
#define CANFD6_IPI_WAKE_MATCH_INTR_NUM                               155
#define CANFD6_IPI_WAKE_TO_INTR_NUM                                  155
#define CANFD6_IPI_BUSOFF_DONE_INTR_NUM                              155
#define CANFD6_IPI_ERROR_FD_INTR_NUM                                 155
#define CANFD7_IPI_BUSOFF_INTR_NUM                                   156
#define CANFD7_IPI_ERROR_INTR_NUM                                    156
#define CANFD7_IPI_MBOR_INTR_NUM                                     156
#define CANFD7_IPI_RX_WARNING_INTR_NUM                               156
#define CANFD7_IPI_TX_WARNING_INTR_NUM                               156
#define CANFD7_IPI_WAKEIN_INTR_NUM                                   156
#define CANFD7_IPI_WAKE_MATCH_INTR_NUM                               156
#define CANFD7_IPI_WAKE_TO_INTR_NUM                                  156
#define CANFD7_IPI_BUSOFF_DONE_INTR_NUM                              156
#define CANFD7_IPI_ERROR_FD_INTR_NUM                                 156
#define CANFD8_IPI_BUSOFF_INTR_NUM                                   157
#define CANFD8_IPI_ERROR_INTR_NUM                                    157
#define CANFD8_IPI_MBOR_INTR_NUM                                     157
#define CANFD8_IPI_RX_WARNING_INTR_NUM                               157
#define CANFD8_IPI_TX_WARNING_INTR_NUM                               157
#define CANFD8_IPI_WAKEIN_INTR_NUM                                   157
#define CANFD8_IPI_WAKE_MATCH_INTR_NUM                               157
#define CANFD8_IPI_WAKE_TO_INTR_NUM                                  157
#define CANFD8_IPI_BUSOFF_DONE_INTR_NUM                              157
#define CANFD8_IPI_ERROR_FD_INTR_NUM                                 157
#define DC1_DC_0_INTR_NUM                                            158
#define DC1_DC_1_INTR_NUM                                            159
#define DC2_DC_0_INTR_NUM                                            160
#define DC2_DC_1_INTR_NUM                                            161
#define DC3_DC_0_INTR_NUM                                            162
#define DC3_DC_1_INTR_NUM                                            163
#define DC4_DC_0_INTR_NUM                                            164
#define DC4_DC_1_INTR_NUM                                            165
#define DC5_DC_0_INTR_NUM                                            166
#define DC5_DC_1_INTR_NUM                                            167
#define DP1_DP_INTR_NUM                                              168
#define DP2_DP_INTR_NUM                                              169
#define DP3_DP_INTR_NUM                                              170
#define MIPI_DSI1_INTR_NUM                                           171
#define MIPI_DSI2_INTR_NUM                                           172
#define CSI1_INTR_NUM                                                173
#define CSI2_INTR_NUM                                                174
#define CSI3_INTR_NUM                                                175
#define MIPI_CSI1_INTR_NUM                                           176
#define MIPI_CSI2_INTR_NUM                                           177
#define G2D1_G2D_INTR_NUM                                            179
#define G2D2_G2D_INTR_NUM                                            180
#define GPU1_INTR_NUM                                                181
#define GPU1_OS_0_INTR_NUM                                           182
#define GPU1_OS_1_INTR_NUM                                           183
#define GPU1_OS_2_INTR_NUM                                           184
#define GPU1_OS_3_INTR_NUM                                           185
#define CANFD9_IPI_BUSOFF_INTR_NUM                                   186
#define CANFD9_IPI_ERROR_INTR_NUM                                    186
#define CANFD9_IPI_MBOR_INTR_NUM                                     186
#define CANFD9_IPI_RX_WARNING_INTR_NUM                               186
#define CANFD9_IPI_TX_WARNING_INTR_NUM                               186
#define CANFD9_IPI_WAKEIN_INTR_NUM                                   186
#define CANFD9_IPI_WAKE_MATCH_INTR_NUM                               186
#define CANFD9_IPI_WAKE_TO_INTR_NUM                                  186
#define CANFD9_IPI_BUSOFF_DONE_INTR_NUM                              186
#define CANFD9_IPI_ERROR_FD_INTR_NUM                                 186
#define CANFD9_IPI_CE_INTR_NUM                                       186
#define CANFD9_IPI_NCEHA_INTR_NUM                                    186
#define CANFD9_IPI_NCEFA_INTR_NUM                                    186
#define CANFD10_IPI_BUSOFF_INTR_NUM                                  187
#define CANFD10_IPI_ERROR_INTR_NUM                                   187
#define CANFD10_IPI_MBOR_INTR_NUM                                    187
#define CANFD10_IPI_RX_WARNING_INTR_NUM                              187
#define CANFD10_IPI_TX_WARNING_INTR_NUM                              187
#define CANFD10_IPI_WAKEIN_INTR_NUM                                  187
#define CANFD10_IPI_WAKE_MATCH_INTR_NUM                              187
#define CANFD10_IPI_WAKE_TO_INTR_NUM                                 187
#define CANFD10_IPI_BUSOFF_DONE_INTR_NUM                             187
#define CANFD10_IPI_ERROR_FD_INTR_NUM                                187
#define CANFD10_IPI_CE_INTR_NUM                                      187
#define CANFD10_IPI_NCEHA_INTR_NUM                                   187
#define CANFD10_IPI_NCEFA_INTR_NUM                                   187
#define CANFD11_IPI_BUSOFF_INTR_NUM                                  188
#define CANFD11_IPI_ERROR_INTR_NUM                                   188
#define CANFD11_IPI_MBOR_INTR_NUM                                    188
#define CANFD11_IPI_RX_WARNING_INTR_NUM                              188
#define CANFD11_IPI_TX_WARNING_INTR_NUM                              188
#define CANFD11_IPI_WAKEIN_INTR_NUM                                  188
#define CANFD11_IPI_WAKE_MATCH_INTR_NUM                              188
#define CANFD11_IPI_WAKE_TO_INTR_NUM                                 188
#define CANFD11_IPI_BUSOFF_DONE_INTR_NUM                             188
#define CANFD11_IPI_ERROR_FD_INTR_NUM                                188
#define CANFD11_IPI_CE_INTR_NUM                                      188
#define CANFD11_IPI_NCEHA_INTR_NUM                                   188
#define CANFD11_IPI_NCEFA_INTR_NUM                                   188
#define CANFD12_IPI_BUSOFF_INTR_NUM                                  189
#define CANFD12_IPI_ERROR_INTR_NUM                                   189
#define CANFD12_IPI_MBOR_INTR_NUM                                    189
#define CANFD12_IPI_RX_WARNING_INTR_NUM                              189
#define CANFD12_IPI_TX_WARNING_INTR_NUM                              189
#define CANFD12_IPI_WAKEIN_INTR_NUM                                  189
#define CANFD12_IPI_WAKE_MATCH_INTR_NUM                              189
#define CANFD12_IPI_WAKE_TO_INTR_NUM                                 189
#define CANFD12_IPI_BUSOFF_DONE_INTR_NUM                             189
#define CANFD12_IPI_ERROR_FD_INTR_NUM                                189
#define CANFD12_IPI_CE_INTR_NUM                                      189
#define CANFD12_IPI_NCEHA_INTR_NUM                                   189
#define CANFD12_IPI_NCEFA_INTR_NUM                                   189
#define GPU2_INTR_NUM                                                190
#define CANFD13_IPI_BUSOFF_INTR_NUM                                  191
#define CANFD13_IPI_ERROR_INTR_NUM                                   191
#define CANFD13_IPI_MBOR_INTR_NUM                                    191
#define CANFD13_IPI_RX_WARNING_INTR_NUM                              191
#define CANFD13_IPI_TX_WARNING_INTR_NUM                              191
#define CANFD13_IPI_WAKEIN_INTR_NUM                                  191
#define CANFD13_IPI_WAKE_MATCH_INTR_NUM                              191
#define CANFD13_IPI_WAKE_TO_INTR_NUM                                 191
#define CANFD13_IPI_BUSOFF_DONE_INTR_NUM                             191
#define CANFD13_IPI_ERROR_FD_INTR_NUM                                191
#define CANFD13_IPI_CE_INTR_NUM                                      191
#define CANFD13_IPI_NCEHA_INTR_NUM                                   191
#define CANFD13_IPI_NCEFA_INTR_NUM                                   191
#define CANFD14_IPI_BUSOFF_INTR_NUM                                  192
#define CANFD14_IPI_ERROR_INTR_NUM                                   192
#define CANFD14_IPI_MBOR_INTR_NUM                                    192
#define CANFD14_IPI_RX_WARNING_INTR_NUM                              192
#define CANFD14_IPI_TX_WARNING_INTR_NUM                              192
#define CANFD14_IPI_WAKEIN_INTR_NUM                                  192
#define CANFD14_IPI_WAKE_MATCH_INTR_NUM                              192
#define CANFD14_IPI_WAKE_TO_INTR_NUM                                 192
#define CANFD14_IPI_BUSOFF_DONE_INTR_NUM                             192
#define CANFD14_IPI_ERROR_FD_INTR_NUM                                192
#define CANFD14_IPI_CE_INTR_NUM                                      192
#define CANFD14_IPI_NCEHA_INTR_NUM                                   192
#define CANFD14_IPI_NCEFA_INTR_NUM                                   192
#define CANFD15_IPI_BUSOFF_INTR_NUM                                  193
#define CANFD15_IPI_ERROR_INTR_NUM                                   193
#define CANFD15_IPI_MBOR_INTR_NUM                                    193
#define CANFD15_IPI_RX_WARNING_INTR_NUM                              193
#define CANFD15_IPI_TX_WARNING_INTR_NUM                              193
#define CANFD15_IPI_WAKEIN_INTR_NUM                                  193
#define CANFD15_IPI_WAKE_MATCH_INTR_NUM                              193
#define CANFD15_IPI_WAKE_TO_INTR_NUM                                 193
#define CANFD15_IPI_BUSOFF_DONE_INTR_NUM                             193
#define CANFD15_IPI_ERROR_FD_INTR_NUM                                193
#define CANFD15_IPI_CE_INTR_NUM                                      193
#define CANFD15_IPI_NCEHA_INTR_NUM                                   193
#define CANFD15_IPI_NCEFA_INTR_NUM                                   193
#define CANFD16_IPI_BUSOFF_INTR_NUM                                  194
#define CANFD16_IPI_ERROR_INTR_NUM                                   194
#define CANFD16_IPI_MBOR_INTR_NUM                                    194
#define CANFD16_IPI_RX_WARNING_INTR_NUM                              194
#define CANFD16_IPI_TX_WARNING_INTR_NUM                              194
#define CANFD16_IPI_WAKEIN_INTR_NUM                                  194
#define CANFD16_IPI_WAKE_MATCH_INTR_NUM                              194
#define CANFD16_IPI_WAKE_TO_INTR_NUM                                 194
#define CANFD16_IPI_BUSOFF_DONE_INTR_NUM                             194
#define CANFD16_IPI_ERROR_FD_INTR_NUM                                194
#define CANFD16_IPI_CE_INTR_NUM                                      194
#define CANFD16_IPI_NCEHA_INTR_NUM                                   194
#define CANFD16_IPI_NCEFA_INTR_NUM                                   194
#define CANFD17_IPI_BUSOFF_INTR_NUM                                  195
#define CANFD17_IPI_ERROR_INTR_NUM                                   195
#define CANFD17_IPI_MBOR_INTR_NUM                                    195
#define CANFD17_IPI_RX_WARNING_INTR_NUM                              195
#define CANFD17_IPI_TX_WARNING_INTR_NUM                              195
#define CANFD17_IPI_WAKEIN_INTR_NUM                                  195
#define CANFD17_IPI_WAKE_MATCH_INTR_NUM                              195
#define CANFD17_IPI_WAKE_TO_INTR_NUM                                 195
#define CANFD17_IPI_BUSOFF_DONE_INTR_NUM                             195
#define CANFD17_IPI_ERROR_FD_INTR_NUM                                195
#define CANFD17_IPI_CE_INTR_NUM                                      195
#define CANFD17_IPI_NCEHA_INTR_NUM                                   195
#define CANFD17_IPI_NCEFA_INTR_NUM                                   195
#define CANFD18_IPI_BUSOFF_INTR_NUM                                  196
#define CANFD18_IPI_ERROR_INTR_NUM                                   196
#define CANFD18_IPI_MBOR_INTR_NUM                                    196
#define CANFD18_IPI_RX_WARNING_INTR_NUM                              196
#define CANFD18_IPI_TX_WARNING_INTR_NUM                              196
#define CANFD18_IPI_WAKEIN_INTR_NUM                                  196
#define CANFD18_IPI_WAKE_MATCH_INTR_NUM                              196
#define CANFD18_IPI_WAKE_TO_INTR_NUM                                 196
#define CANFD18_IPI_BUSOFF_DONE_INTR_NUM                             196
#define CANFD18_IPI_ERROR_FD_INTR_NUM                                196
#define CANFD18_IPI_CE_INTR_NUM                                      196
#define CANFD18_IPI_NCEHA_INTR_NUM                                   196
#define CANFD18_IPI_NCEFA_INTR_NUM                                   196
#define CANFD19_IPI_BUSOFF_INTR_NUM                                  197
#define CANFD19_IPI_ERROR_INTR_NUM                                   197
#define CANFD19_IPI_MBOR_INTR_NUM                                    197
#define CANFD19_IPI_RX_WARNING_INTR_NUM                              197
#define CANFD19_IPI_TX_WARNING_INTR_NUM                              197
#define CANFD19_IPI_WAKEIN_INTR_NUM                                  197
#define CANFD19_IPI_WAKE_MATCH_INTR_NUM                              197
#define CANFD19_IPI_WAKE_TO_INTR_NUM                                 197
#define CANFD19_IPI_BUSOFF_DONE_INTR_NUM                             197
#define CANFD19_IPI_ERROR_FD_INTR_NUM                                197
#define CANFD19_IPI_CE_INTR_NUM                                      197
#define CANFD19_IPI_NCEHA_INTR_NUM                                   197
#define CANFD19_IPI_NCEFA_INTR_NUM                                   197
#define CANFD20_IPI_BUSOFF_INTR_NUM                                  198
#define CANFD20_IPI_ERROR_INTR_NUM                                   198
#define CANFD20_IPI_MBOR_INTR_NUM                                    198
#define CANFD20_IPI_RX_WARNING_INTR_NUM                              198
#define CANFD20_IPI_TX_WARNING_INTR_NUM                              198
#define CANFD20_IPI_WAKEIN_INTR_NUM                                  198
#define CANFD20_IPI_WAKE_MATCH_INTR_NUM                              198
#define CANFD20_IPI_WAKE_TO_INTR_NUM                                 198
#define CANFD20_IPI_BUSOFF_DONE_INTR_NUM                             198
#define CANFD20_IPI_ERROR_FD_INTR_NUM                                198
#define CANFD20_IPI_CE_INTR_NUM                                      198
#define CANFD20_IPI_NCEHA_INTR_NUM                                   198
#define CANFD20_IPI_NCEFA_INTR_NUM                                   198
#define VPU1_O_VPU_INTR_NUM                                          199
#define VPU2_O_HOST_INTR_NUM                                         200
#define MJPEG_O_REQ_INTR_NUM                                         201
#define CE1_CE0_O_INTR_NUM                                           204
#define CE1_TRNG_INTR_NUM                                            205
#define CE2_CE0_O_INTR_NUM                                           207
#define CE2_CE1_O_INTR_NUM                                           208
#define CE2_CE2_O_INTR_NUM                                           209
#define CE2_CE3_O_INTR_NUM                                           210
#define CE2_CE4_O_INTR_NUM                                           211
#define CE2_CE5_O_INTR_NUM                                           212
#define CE2_CE6_O_INTR_NUM                                           213
#define CE2_CE7_O_INTR_NUM                                           214
#define CE2_TRNG_INTR_NUM                                            215
#define DDR_SS_DDR_SS_INTR_NUM                                       218
#define WDT1_ILL_WIN_REFR_INTR_NUM                                   219
#define WDT1_ILL_SEQ_REFR_INTR_NUM                                   219
#define WDT1_OVFLOW_INTR_NUM                                         220
#define WDT3_ILL_WIN_REFR_INTR_NUM                                   221
#define WDT3_ILL_SEQ_REFR_INTR_NUM                                   221
#define WDT3_OVFLOW_INTR_NUM                                         222
#define WDT8_ILL_WIN_REFR_INTR_NUM                                   223
#define WDT8_ILL_SEQ_REFR_INTR_NUM                                   223
#define WDT8_OVFLOW_INTR_NUM                                         224
#define TIMER1_CHN_INTR_NUM                                          225
#define TIMER1_OVF_INTR_NUM                                          226
#define TIMER2_CHN_INTR_NUM                                          227
#define TIMER2_OVF_INTR_NUM                                          228
#define TIMER3_CHN_INTR_NUM                                          229
#define TIMER3_OVF_INTR_NUM                                          230
#define TIMER4_CHN_INTR_NUM                                          231
#define TIMER4_OVF_INTR_NUM                                          232
#define TIMER5_CHN_INTR_NUM                                          233
#define TIMER5_OVF_INTR_NUM                                          234
#define TIMER6_CHN_INTR_NUM                                          235
#define TIMER6_OVF_INTR_NUM                                          236
#define TIMER7_CHN_INTR_NUM                                          237
#define TIMER7_OVF_INTR_NUM                                          238
#define TIMER8_CHN_INTR_NUM                                          239
#define TIMER8_OVF_INTR_NUM                                          240
#define ADC_INTR_NUM                                                 240
#define PWM1_PWM_INTR_NUM                                            241
#define PWM2_PWM_INTR_NUM                                            242
#define PWM3_PWM_INTR_NUM                                            243
#define PWM4_PWM_INTR_NUM                                            244
#define PWM5_PWM_INTR_NUM                                            245
#define PWM6_PWM_INTR_NUM                                            246
#define PWM7_PWM_INTR_NUM                                            247
#define PWM8_PWM_INTR_NUM                                            248
#define RTC1_RTC_WAKEUP_INTR_NUM                                     249
#define RTC1_RTC_PERIODICAL_INTR_NUM                                 250
#define RTC1_VIOLATION_INTR_NUM                                      251
#define RTC2_RTC_WAKEUP_INTR_NUM                                     252
#define RTC2_RTC_PERIODICAL_INTR_NUM                                 253
#define RTC2_VIOLATION_INTR_NUM                                      254
#define TM_VIOLATION_INTR_NUM                                        255
#define PVT_SNS_SEC_PVT_0_INTR_NUM                                   260
#define PVT_SNS_SEC_PVT_1_INTR_NUM                                   261
#define PVT_SNS_SAF_PVT_0_INTR_NUM                                   262
#define PVT_SNS_SAF_PVT_1_INTR_NUM                                   263
#define MU_MU_MESSAGE_READY_INTR_NUM                                 264
#define MU_MU_WAKEUP_INTR_NUM                                        265
#define MU_SEMAPHORE_LOCK_FAIL_INTR_NUM                              266
#define MU_SEMAPHORE_LOCK_STATUS_CHANGE_INTR_NUM                     267
#define GPIO2_GPIO_0_INTR_NUM                                        268
#define GPIO2_GPIO_1_INTR_NUM                                        269
#define GPIO2_GPIO_2_INTR_NUM                                        270
#define GPIO2_GPIO_3_INTR_NUM                                        271
#define GPIO2_GPIO_4_INTR_NUM                                        272
#define GPIO2_GPIO_5_INTR_NUM                                        273
#define IRQ_MAX_INTR_NUM                                             274


#endif /* IRQ_NUM_H */
